# Generated by Django 3.0.5 on 2020-05-25 15:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebooks',
            name='issuedate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuebooks',
            name='returndate',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 15, 45, 29, 148717)),
        ),
    ]
