# Generated by Django 3.0.5 on 2020-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
