# Generated by Django 3.0.5 on 2020-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200523_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
